Create hello microverse Repository
jerymey/Hello pull request #1
Opened 2023-07-04 23:38 UTC by jerymey

**In this project, I did the following :**

- [ ] Created branch
- [ ] Used correct github flow
- [ ] added linters
- [ ] Customize Readme.md file
- [ ] Created html and css files

2023-07-04 23:46 UTC, DuaneDave requested changes
Hi @jerymey  👋 , 

Good job so far on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Correct use of GitHub flow
✔️ Linters are set up correctly and all checks are green

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-04 23:46 UTC, DuaneDave commented on .gitignore
> +node_modules/
According to the requirements, the test.md file which is currently appearing in your project structure should have been ignored here, consider listing it here as you have done with the node_modules file in order to fulfil the requirements

2023-07-05 00:26 UTC, shahadat3669 requested changes
Hi @jerymey,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media0.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

 ## Highlights
✅ Follow reviewer request 👍 
✅ Good PR title .
✅ Good PR description.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
you can consider the following for the next project:

- [ ] [Optional] Great work on your project! 👍 However, there is a small suggestion for your future projects. It is recommended to follow the [GitHub flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md) properly by using "main" as the base branch name instead of "master". This aligns with the industry's best practices and promotes inclusive and respectful language. Remember to keep this in mind for your upcoming projects. Keep up the good work! 💪


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-05 00:26 UTC, shahadat3669 commented on test.md
As per the previous reviewer's request, you added "test.md" to the .gitignore file. However, I noticed that this file still exists in the GitHub repository. Please remove the "test.md" file to ensure it is properly excluded from version control. You can refer to the documentation provided [here](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files) for further assistance on ignoring files in Git. Thank you! 👍

2023-07-05 00:26 UTC, shahadat3669 commented on README.md
- [ ] [Optional] Well done on adding the 'Readme file!👍 However, it would be good to add "future features" and include 1-3 potential features in this section. Remember in this section, you should outline your plans for the future development of the project. Include details about the features, functionalities, or improvements you intend to add. It should demonstrate your vision and give readers an idea of what to expect. Keep up the good work! Please include 1-3 potential fractures in this section.

 ![image](https://github.com/2004-okari/HELLO_MICROVERSE/assets/55840999/6c06d9c5-1153-4928-bfd9-d55057f77c97) 

- [ ] [Optional] it seems that you have overlooked removing the key features from the README template. Kindly add meaningful and comprehensive list of the key features of your project. This will provide readers with a clear understanding of what your project has to offer.

2023-07-06 11:08 UTC, V-Blaze approved these changes
Hi @jerymey  , 

# Approved 🟢 🟢 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![giphy](https://user-images.githubusercontent.com/107632780/229644741-7dea3027-bf3f-4416-855b-46095e3bf6d5.gif)

## Highlights

- Linters setup correctly💯
-  Correct GitHub flow👍
-  Readme looks professional🟢 👍

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-06 11:09 UTC, merged